baseURL = "https://example.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
theme = "lightning"
title = "Website Title"
enableEmoji = true

[languages.en]
  languageName = "English"
  languageCode = "en-us"
  weight = 1

[outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  defaultImage = "/images/lightning.svg"
  deploy_commit = ""
  deploy_ref = ""
  deploy_time = ""

[params.lightning]
  sidePane = true
  showSharelinks = true
  showReplyByMail = true
  countPageItems = 7
  footerCommitAndTime = true
  footerScrollToTop = true
  footerPoweredBy = false

[params.lightning.info]
  authorImg = "/images/profile.jpg"
  authorName = "First-Name"
  authorFullName = "Full Name"
  username = "Username"
  subHeading = "hugo theme"
  subHeadingLocation = "from City, Country"
  countryEmoji = "üåè"
  currentOccupation = "Current Job at"
  companyName = "ACME"
  companyURL = "https://example.com/"
  copyrightStartYear = 2025
  replyEmail = "hello@sample.com"

[params.lightning.home]
  showBio = true
  showAuthorImg = true
  showHomeBanner = false
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5
  showSocialLinks = true

[params.lightning.side.home]
  sidePaneSticky = false
  taxonomies = ["tags"]
  countTaxonomy = 5

[params.lightning.side.single]
  sidePaneSticky = true
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 20

[related]
  includeNewer = true

[[related.indices]]
  name = "tags"
  weight = 100
