name = 'Lightning'
license = 'GPL-3.0'
licenselink = 'https://github.com/ThunderE75/hugo-lightning/blob/main/LICENSE'
description = 'A reimagined hugo theme'

homepage = 'https://github.com/ThunderE75/hugo-lightning'
demosite = 'https://thundere75.github.io/'

tags = ["responsive", "minimal", "blog"]
features = ["blog", "themes", "search"]

[author]
  name = 'ThunderE75'
  homepage = 'https://github.com/ThunderE75'
