baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lightning Theme'
theme = 'lightning'
themesdir = '../..'

[markup.goldmark.renderer]
unsafe= true # to enable raw HTML in markdown files